simulation_config:
  epsilon_setting: "fixed"
  epsilon_type: "continuous"
  explore_mode: "Normal"
  initialization_rejection_sampling_flag: False
  gui_flag: False
  map: "3Lane"
  neuralmetric_flag: True
  neuralmetric_config:
    experiment_name: "3_model_0s_before_unavoidable_split_pos_neg_newnormalize"
    dataset: "neuralmetric_iter1/unavoidablebefore05s/splitdata_newnormalize"
    label: "Random sample 3 model 0s before unavoidable"
    validation_data_path: "neuralmetric_iter1/unavoidablebefore05s/"
    load_dataset_method: "split_pos_neg"
    validation_save_result_root_path: "neuralmetric_iter1/unavoidablebefore05s"
    loss_func: "BCE"
    batch_size: 128
    max_num_epochs: 4000
    lr: 0.005
    model: 'bn_mlp_sigmoid'
    DSL_mode: "baseline"
    layer_num: 1
    num_workers: 0
    ckpt: "./agents/NeuralMetric/best_ckpt.pt"
    obs_normalize: True
    input_dim: 27
  pytorch_model_path_list: 
    - "./agents/AV/basemodel_ckpt369.pt"
    - "./agents/AV/basemodel_ckpt369.pt" # please set this variable to be the path to your trained agent for three-lane highway scenario, initialized to be the same as the base model
  pytorch_nade_model_path: "./agents/ITE/nademodel099_cp927.pt"
  safetyguard_flag: True
  speed_mode: "high_speed"

experiment_config:
  AV_model: "RLNew"
  code_root_folder: "."
  experiment_name: "testing" # please set this variable to be any experiment name you want
  episode_num: 20000
  lr: 0.00001 
  log_mode: "offlinecollect"
  mode: "NADE"
  root_folder: "./output" # please set this variable to be the path where you want to store the evaluation results
  train_flag: False